### ISSUE TITLE
Chargement en boucle de "critical.css" par le Service Worker

### ISSUE THREAD

**Issue by jbleuzen** [borisschapira/boris.schapira.dev#376]
Bonjour Boris,

Ça fait plusieurs fois que je remarque que l’onglet courant de mon navigateur Safari plante et recharge l’onglet lorsque je visite ton site.
Aujourd’hui c’était sur Safari iOS mais j’ai eu le même soucis sur Safari Mac.

Mes 2 machines sont à jour.

![01BE160F-E2CD-496D-AAD5-627DE32DB73F](https://user-images.githubusercontent.com/280681/80829677-df670b80-8be7-11ea-9595-6f2705393442.png)

**Comment by borisschapira** [comment]
Hello Johan,

Tout d'abord, merci énormément d'avoir pris du temps pour remonter ce problème dont je n'avais pas idée. Je teste régulièrement sur Safari Mac (à jour également), sans souci. Mais comme j'ai un peu joué avec les Service Workers, si ça se trouve, l'état sauvegardé dans ton navigateur n'est pas le bon (j'en suis désolé). 

Est-ce que tu serais en mesure de pousser plus loin avec deux tests ?

- Tester dans une fenêtre de navigation privée et voir si ça se produit aussi
- Sur n'importe quelle page, ouvrir les outils de développement et exécuter dans la Console :

  ```
  navigator.serviceWorker.getRegistrations().then(function(registrations) {
   for(let registration of registrations) {
    registration.unregister()
  }})
  ```

  Cette portion de code supprimera le Service Worker. En rechargeant la page, est-ce que le bug se reproduit ?

Encore une fois, merci énormément d'avoir pris ce temps et désolé de t'en demander davantage.

**Comment by jbleuzen** [comment]
Pas de soucis, pas besoin de s'excuser :) 
Si je n'avais pas vu le bouton sur ton site je ne t'aurai pas fait de retour, mais la je me suis dit go !

Je ne pouvais pas regarder avec les devtools, mais la j'ai pris le temps de regarder cette fois et j'ai plus de précisions sur le problème que je rencontre. En gros les Service Workers téléchargent en boucle le fichier `critical.css` aussi bien en privé qu'en onglet normal. 

<img width="1680" alt="Screenshot 2020-05-02 at 14 02 58" src="https://user-images.githubusercontent.com/280681/80863655-1ee03700-8c7e-11ea-991f-64b2a7ce4416.png">

J'ai essayé de supprimer le Service Worker mais le comportement continue.

Pour info, sur Chrome ce fichier est télécharger 2 fois mais c'est tout.

Bonne journée,

**Comment by borisschapira** [comment]
Et voilà !

Pour moi-même : j'ai voulu utiliser les directives `preload` et `preconnect` via des en-têtes HTTP. J'ai configuré ces en-têtes dans Netlify **sauf** que Netlify ne permet pas de définir des en-têtes uniquement pour les documents, ces directives étaient donc passées avec toutes les ressources.

Lors du premier chargement de la page :

1. Chargement de la page. Elle indique un `preload` sur critical.css donc…
2. Chargement de critical.css. Il indique un `preload` sur lui-même donc…
3. Rien, car le navigateur détecte que la récursivité.

Lors du second chargement de la page : 

1. Le Service Worker sert la page en cache. La page en cache indique un `preload` sur critical.css donc…
2. Chargement de critical.css, servi par par le Service Worker. Il indique un `preload` sur lui-même donc…
3. Début du zbeul, car pour le navigateur, le critical.css servi par le SW n'est pas critical.css, donc il relance le téléchargement. Et c'est à nouveau le Service Worker qui y répond, donc on boucle sur les phases 2 et 3.

Correction : 

- suppression des directives via en-têtes HTTP, je les ai mise en HTML à la place.
- attente de correction sur Netlify https://community.netlify.com/t/setting-response-headers-only-on-documents/6144/20

Alternative si ça ne se corrige pas chez eux : configurer le SW pour qu'il fasse sauter les directives de `preload` et `preconnect` sur les resources qui ne sont pas des documents, quand il les met en cache. Mais c'est du boulot, et j'ai la flemme.

**Comment by nhoizey** [comment]
Cool, j'ai aussi appris une limite des en-têtes de Netlify, alors que j'avais dans l'idée d'en mettre, merci ! 😅
