### ISSUE TITLE
Article "/2020/06/des-termes-problematiques/"

### ISSUE THREAD

**Issue by KewlCat** [borisschapira/boris.schapira.dev#394]
Coucou !

J'ai repéré une petite faute dans ce très intéressant article : 

Celleux qui soutiennent le changement ou se placeront dans une posture d’opposition verront leurs revendications sur un échiquier politique, qu’ils le veuille ou non.

=> "qu'ils le veuillent"

**Comment by borisschapira** [comment]
Merci !
