### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mlcdf** [borisschapira/boris.schapira.dev#848]
Salut Boris, 

Il me semble qu'il y a une typo ici :

https://github.com/borisschapira/boris.schapira.dev/blob/901f614bf4f22246591e54d0623794b096cd919c/_pages/fr/a-propos/site.md?plain=1#L16

```
performances web du site.lancés sur ce site").
```

**Comment by borisschapira** [comment]
Fixed! Merci !

**Comment by nhoizey** [comment]
@borisschapira au passage, tu peux passer l'URL de mon site en HTTPS, même s'il est dans les listes HSTS Preload… 😅
